version: '3.8'

services:
  ecommerce:
    image: openjdk:21-jdk
    container_name: ecommerce
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - .:/app
    working_dir: /app
    command: ["mvn", "spring-boot:run"]