version: '3.8'

services:
  ecommerce:
    build: .
    container_name: ecommerce
    ports:
      - "8080:8080"
    env_file:
      - etc/.env
    volumes:
      - ~/.aws/:/root/.aws:ro
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.6-alpine3.21
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - ./etc/database:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ecommerce" ]
      interval: 5s
      timeout: 4s
      retries: 5