server:
  servlet:
    context-path: /api
  port: 8080

aws:
  sns:
    topic-arn: ${TOPIC_ARN}

spring:
  application:
    name: e-commerce
  web:
    resources:
      add-mappings: false
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      leak-detection-threshold: 2000
      pool-name: HikariPool
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.default_schema: ${DB_SCHEMA}
logging:
  level:
    root: INFO
    dev.waltercrdz.api: INFO
    com.zaxxer.hikari: DEBUG
    org.hibernate: DEBUG