name: E-commerce CI/CD

on: [ push, pull_request ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and Test with Maven
        run: |
          chmod +x ./mvnw
          ./mvnw clean package
          ./mvnw test