name: E-commerce CI/CD

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-23.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'openjdk'
          cache: 'maven'

      - name: Build with Make
        run: make build

      - name: Run tests
        run: make test